services:
  synctask:
    image: synctask
    volumes:
      - D:/Dockerbox/Source:/app/source
      - D:/Dockerbox/Target:/app/target
      - D:/Dockerbox/:/app
    entrypoint: ["dotnet", "SyncTask.dll", "/app/source", "/app/target", "/app/log.txt", "5"]